spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8181
mybatis-plus:
  mapper-locations: classpath:/com/southwind/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl